### ISSUE TITLE
wallet-rpc get_transfers response missing field

### ISSUE THREAD

**Issue by ccdonn** [loki-project/loki-core#1253]
**Describe the bug**

response of get_transfers some field are missing
example: destinations

**To Reproduce**
call get_transfers rpc

**Expected behaviour**
What is the expected behaviour if the steps above are followed:

https://docs.loki.network/Developer/WalletRPCBeta/#command_rpc_get_transfers

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:

see Logs

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

```
{
      "address": "T6ThQHx6CfN9oLfinP2n8S96MYijbPbXpWrfX783g4pCGf1WWKnthVSgrSzdJ1Ph2MFdUgUt2DiDW1kWJrxmNqg116j2i1mYe",
      "amount": 10000,
      "blink_mempool": false,
      "checkpointed": 1,
      "confirmations": 601,
      "double_spend_seen": false,
      "fee": 100710480,
      "height": 378986,
      "note": "",
      "payment_id": "0000000000000000",
      "subaddr_index": {
        "major": 0,
        "minor": 0
      },
      "subaddr_indices": [{
        "major": 0,
        "minor": 0
      }],
      "suggested_confirmations_threshold": 1,
      "timestamp": 1600081618,
      "txid": "f36517f2ede4d2e03dc245fe08bc92bbc241021819bf4e60cdc5c03313cab04e",
      "type": "out",
      "unlock_time": 0,
      "was_blink": false
    }
```

**Additional Information (please complete the following information):**
 - Operating System: Centos 7
-  Local or Remote node: i run a testnet fullnode myself, and use the wallet-rpc on the same server
 - Version of Loki daemon, or most recent commit hash: Valiant Vidar 7.1.9

**Comment by Doy-lee** [comment]
I suspect this is because the wallet did not get saved when the transfer was sent, or the wallet was recovered by seed or reset using rescan_bc <hard> or some sort.

The destination address is lost if it's doesn't get a chance to save it to the wallet cache (which is should automatically but, you never know). The reason being that all transactions are sent to a stealth address, and that's what is stored on the blockchain. Hence when you go to rescan the blockchain for your wallet, the only information on the blockchain is the stealth address and not their wallet so you can't recreate the missing data.

You can try and verify this by re-sending a new transaction and observing the output of get_transfers, also ensuring that if you are exiting the wallet, you exit the wallet using the exit command to ensure it saves the data to disk rather than a kill signal for example which might skip the save step.

**Comment by ccdonn** [comment]
trying to use binary built from dev branch with the same progress, and `destinations` field shows up.
so, the question would be what if i do the same thing on mainnet.

anyway, let me temporary close the issue.
thanks for help.
