### ISSUE TITLE
Expose RPC endpoint for print_sn_status

### ISSUE THREAD

**Issue by jcktm** [loki-project/loki-core#233]
> (although it is just a wrapper around print_sn)

**Comment by darcys22** [comment]
So `t_command_parser_executor::print_sn_status` is in the daemonize namespace. To call this from `core_rpc_server` I think will result in a circular reference.

Also the current print_sn simply writes to cout so will likely need to be modified to return something that can be passed in the rpc response.

where would the best place be to move the print_sn_status call so that both the daemon and the rpc can call it? or can this be done in the daemonize namespace anyway?

**Comment by Doy-lee** [comment]
This issue is actually for adding a JSON RPC endpoint for `print_sn_status`. In which case most of the infrastructure is already there don't need to re-write too much. 

Just need to add the endpoint in `core_rpc_server.h` and map the "get_service_node_status" string to a new core_rpc_server function, `on_get_service_node_status`. Create the request and response structure in `core_rpc_server_command_defs.h`

Then you'd move the work of generating the response to the RPC request in `core_rpc_server::on_get_service_node_status`, followed by updating `t_rpc_command_executor` to call into `core_rpc_server` to DRY the logic.

Now ideally we actually want to move to deprecating `get_service_nodes*` and its children and switch to `get_n_service_nodes` as it's better designed. But one step at a time.

**Comment by javabudd** [comment]
can this be closed?

**Comment by darcys22** [comment]
Yeah this was merged
