### ISSUE TITLE
Tiered Loki Unlock Fee Structure- Emission Offset

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/loki-core#752]
**Idea:**
Give Full Node Operators (100%) the option to de-register their Loki Stake for a higher fee. All fees from these unlocks will burnt to help offset the Loki Emissions. 

**Current Unlock Structure:** 

A Node Operator requests an unlock which incurs a 15 day wait for loki unlocking with no fee.

**Proposed Unlock Structure:** 

A Node Operator elects to get an early release of their Loki for whatever purpose; this incurs a fee  that will be burnt. 

15 day Unlock- This remains free
10 Day Unlock- Burn 2% of the Loki in the service node
5 Day Unlock -Burn 4% of the Loki in the Service Node
0 Day Unlock- Burn 10% of the Loki in the Service Node

Pros: Helps reduce emissions and offset block reward

Cons: 
The decreased unlock time could reduce the stability of the network 
The feature will not be attractive and no one will use it
Development time and resources will be needed to implement and explain

Happy to hear any comments on the idea.

**Comment by KeeJef** [comment]
I like this idea, but i wonder if anyone would actually use it? the fee would have to be sufficiently high so that in periods of high price fluctuations we didn't see large swings in the node count which could adversely affect network stability. At that point the fee might be so high that Service Node operators just choose to wait, which means we just added more complexity to the protocol while getting the same result as we already have, albeit node operators now have more choice.
i might ask this question is the Service Node chats:
"Would operators be interested in burning some Loki to unlock faster"

**Comment by jagerman** [comment]
This could be interesting for deregistered service nodes: if you get deregistered, you either do your time or pay a fine.

**Comment by KeeJef** [comment]
> This could be interesting for deregistered service nodes: if you get deregistered, you either do your time or pay a fine.

Actually i think that is a more compelling case, since i can think of times where i didnt want to wait but would have paid a fine

**Comment by CryptoFirefly** [comment]
I agree on the network stability, active nodes should not have a quick and easy way out. That could trigger two issues at the same time, reduce node count and could have service level quality issues with reduced nodes and it could have an instant sell pressure. 

The proposal on de-reg nodes sounds like a good idea. Instead of a 30-day lock, if we allow them to unlock and restake it actually improves the network and node count. (Which is a good thing).
And to fairly adjust for penalty buring loki benefits everyone in the eco-system. 

The fee for de-reg nodes to unlock Loki instantly should be somewhat close to 30 days of reward which we forcing them to lose. A fixed figure like 10% or even 5% would be too high and as node returns are dynamic and likely node returns will drop below 2% or 1% in near future, so the fee payable should be dynamic. We can offer a quick calculator to allow de-reg node’s members to calculate and take a call. 

A formula which may work. It could be driven by parameters such as
A. Block Reward for SNs
B. Blocks across 30 Days
C. No. of Active Nodes
D. 20% Surcharge vs possible rewards = 20% of (A x B) / C
E: Stake % in Node

Unlock Fee = [ ( (A x B ) / C ) + D ] x E

Today's example for a Solo Node:
A = 15.68
B = 720 x 30 = 21600
C = 665
D = 20%
E = 100%
Unlock Fee 	= [(15.68 x 21600) / 665 + D ] x E		
		= ( 509 * 101.8 ) x E
		= 610.8 x 100%
		= 610.8 Loki

What we need to decide in the above is the value for “D”, is 20% a fair penalty, or maybe 25%. This formula would work all scenarios. 

And English or Easy explanation for this to the Operators and Contributors is = “Now you have an option to unlock your loki by paying a fee which is approx. = Rewards you would have earned + 20% penalty on it.”
Net net the real loss is 20% penalty in above case for them, as these guys can unlock and re-stake instantly. 

Will be good for the network incase of mass de-reg. And good with deflationary burn effect. 
Also fee payable would be proportion to the stake %, and each contributor has the decision in their own hands.

Further thoughts needed
1.	How to make it easy for a de-reg Node to still be visible on loki-blocks in that status until the stakes unlock after 30days or until all participants have unlocked their stake.
Penalty %. 20 or 25 or 30%. What’s a fair parameter.

**Comment by CryptoFirefly** [comment]
And yes, to make it simple we could keep this formula fixed across the 30 days. So its wise for the Operator and Contributors to take a call quickly in the first few days. If they decide to use this option on 28th day after de-reg, they pay the then applicable fee _(likely similar range if done on the 1st day, maybe slightly lower if node count increased)._  But they are paying that amount only to unlock 2 days ahead of schedule. 

If the above formula works well, extending to active Solo ONLY nodes could be considered.

Keeping the formula same, would discourage Solo ops from rushing to instant unstake and unlock... as they'd be paying 20% over a 30 days possible reward vs waiting only 15 days in a planned unstake.
